RankLLM Refactor
castorini/rank_llm pull request #126
Opened 2024-07-26 03:27 UTC by xpbowler

2024-07-26 11:08 UTC, ronakice requested changes
I've left my first set of comments will look more after!

2024-07-26 11:08 UTC, ronakice commented on requirements.txt
> +dacite==1.8.1
Let's go with >=, I like some flexibility and models grow too fast

2024-07-26 11:08 UTC, ronakice commented on src/rank_llm/demo/rerank_rank_gpt.py
>  from rank_llm.rerank.rank_gpt import SafeOpenai
this path changes?

2024-07-26 11:08 UTC, ronakice commented on src/rank_llm/rerank/listwise/gpt/rank_gpt.py
> +                "content": "You are RankGPT, an advanced assistant specialized in ranking passages by their relevance to a given query.",
Why is this changing? It should be what is in the main branch

2024-07-26 11:08 UTC, ronakice commented on src/rank_llm/rerank/listwise/gpt/rank_gpt.py
> +        return f"Search Query: {query}.\nArrange the {num} passages above in order of relevance to the search query, from most to least relevant. Use the numerical identifiers for ranking. The format
I feel a lot of this is different in main branch, please take a look

2024-07-26 14:30 UTC, sahel-sh commented on src/rank_llm/retrieve_and_rerank.py
> +                **kwargs,
Have you tested this cl with unexpected keys in kwargs? I expect passing kwargs here, without changing the `rerank_batch`  would simply flatten the kwargs elements as keyword parameters and raise type error.
Both rerank and rerank_batch functions should take **kwargs as input and properly filter it (similar to what you are doing in the get_reranker and retrive function here).

2024-07-26 14:30 UTC, sahel-sh commented on src/rank_llm/retrieve_and_rerank.py
> -            print("Evaluating:")
why are you removing these evals
[general tip]: Always aim to separate refactoring from logical changes unless the logical change is the goal of the refactoring (e.g. using a new library that introduces a new dependency, etc).

2024-07-26 15:08 UTC, sahel-sh reviewed
@xpbowler I had missed to open some of the diffs that were not automatically loaded. I resolved a couple of my previous comments, sorry about that!

2024-07-26 15:08 UTC, sahel-sh commented on src/rank_llm/rerank/reranker.py
> -class Reranker:
IIUC, you are removing the Reranker class and add rerank and rerank_batch to the RankLLM class. 
hm, I am not sure if we want this. I kind of like a Reranker class that has a ranking agent. For example, writing the reranking ressults can be a task of the reranker, but not the ranking agent.
WDYT? @ronakice

2024-07-26 15:08 UTC, sahel-sh commented on src/rank_llm/rerank/reranker.py
> -class Reranker:
We might also have Rerankers with other agents. For example, our Identity and Random rerankers do not inherit from rankllm but still need to implement the rerank and rerank_batch methods.

2024-07-30 02:12 UTC, sahel-sh commented on src/rank_llm/retrieve/retriever.py
> -        if not isinstance(dataset_name, str):
@xpbowler PTAL

2024-07-30 02:13 UTC, sahel-sh commented on src/rank_llm/demo/experimental_results.py
> +g_reranker = SafeOpenai("gpt-3.5-turbo", 4096, keys=get_openai_api_key())
@xpbowler PTAL

2024-07-30 02:14 UTC, sahel-sh commented on src/rank_llm/retrieve_and_rerank.py
> +    if agent is None:
Please address this @xpbowler

2024-07-30 02:17 UTC, sahel-sh commented on src/rank_llm/rerank/rankllm.py
> -        self._context_size = context_size
@xpbowler PTAL

2024-07-30 02:17 UTC, sahel-sh commented on src/rank_llm/rerank/reranker.py
> +        pass_ct: int = None,
@xpbowler PTAL

2024-08-02 03:48 UTC, sahel-sh approved these changes

2024-08-02 04:57 UTC, ronakice commented on src/rank_llm/retrieve/retriever.py
> -        if not isinstance(dataset_name, str):
@xpbowler did you verify this?

2024-08-02 04:59 UTC, ronakice approved these changes
LGTM! but left one comment

2024-08-02 15:02 UTC, ronakice approved these changes
LGTM!

2024-08-02 15:03 UTC, merged