Readme Update with pre-commit Pipeline
castorini/rank_llm pull request #68
Opened 2024-01-30 05:40 UTC by AndreSlavescu

Added complete pipeline to format files before contributing to repository. 

automatically runs black on all files for formatting. 
automatically runs isort on all files for alphabetical ordering.

2024-01-30 06:03 UTC, ronakice commented
I believe changes also need to be made to pyproject.toml?

2024-01-30 13:43 UTC, sahel-sh requested changes

2024-01-30 13:43 UTC, sahel-sh commented on requirements.txt
> -faiss-gpu>=1.7.2
This is needed, I remember I had issues without it. please keep it

2024-01-30 13:43 UTC, sahel-sh commented on pyproject.toml
> -    "faiss-gpu == 1.7.2",
same here, let's not change requirements

2024-01-30 13:52 UTC, sahel-sh commented
As we discussed in the chat, let's keep requirement changes separate. Ronak has already created an issue for it: https://github.com/castorini/rank_llm/issues/66

2024-01-31 21:28 UTC, ronakice commented
@AndreSlavescu can we go about this as Sahel suggested? Sahel has a separate PR addressing this

2024-02-01 03:37 UTC, closed without merging